# Generated by Django 4.1.2 on 2023-03-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthdate', models.DateField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
