# Generated by Django 4.1.2 on 2023-03-18 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
