# Generated by Django 4.1.7 on 2023-03-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='question',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
